import { Address } from '../index';

export const selection: { Items: Address[] } = {
  Items: [
    {
      Id: 'GB|RM|A|21415581',
      DomesticId: '21415581',
      Language: 'ENG',
      LanguageAlternatives: 'ENG,CYM',
      Department: '',
      Company: '',
      SubBuilding: 'Piccardy Flat',
      BuildingNumber: '',
      BuildingName: 'Koolabar',
      SecondaryStreet: '',
      Street: 'Upper Frog Street',
      Block: '',
      Neighbourhood: '',
      District: '',
      City: 'Tenby',
      Line1: 'Piccardy Flat',
      Line2: 'Koolabar',
      Line3: 'Upper Frog Street',
      Line4: '',
      Line5: '',
      AdminAreaName: 'Pembrokeshire',
      AdminAreaCode: '',
      Province: 'Sir Benfro',
      ProvinceName: 'Sir Benfro',
      ProvinceCode: '',
      PostalCode: 'SA70 7JD',
      CountryName: 'United Kingdom',
      CountryIso2: 'GB',
      CountryIso3: 'GBR',
      CountryIsoNumber: 826,
      SortingNumber1: '84144',
      SortingNumber2: '',
      Barcode: '(SA707JD2T3)',
      POBoxNumber: '',
      Label:
        'Piccardy Flat\nKoolabar\nUpper Frog Street\nTENBY\nSA70 7JD\nUNITED KINGDOM',
      Type: 'Residential',
      DataLevel: 'Premise',
      Field1: '',
      Field2: '',
      Field3: '',
      Field4: '',
      Field5: '',
      Field6: '',
      Field7: '',
      Field8: '',
      Field9: '',
      Field10: '',
      Field11: '',
      Field12: '',
      Field13: '',
      Field14: '',
      Field15: '',
      Field16: '',
      Field17: '',
      Field18: '',
      Field19: '',
      Field20: '',
    },
    {
      Id: 'GB|RM|A|21415581',
      DomesticId: '21415581',
      Language: 'CYM',
      LanguageAlternatives: 'ENG,CYM',
      Department: '',
      Company: '',
      SubBuilding: 'Piccardy Flat',
      BuildingNumber: '',
      BuildingName: 'Koolabar',
      SecondaryStreet: '',
      Street: 'Upper Frog Street',
      Block: '',
      Neighbourhood: '',
      District: '',
      City: 'Dinbych-y-Pysgod',
      Line1: 'Piccardy Flat',
      Line2: 'Koolabar',
      Line3: 'Upper Frog Street',
      Line4: '',
      Line5: '',
      AdminAreaName: 'Pembrokeshire',
      AdminAreaCode: '',
      Province: 'Sir Benfro',
      ProvinceName: 'Sir Benfro',
      ProvinceCode: '',
      PostalCode: 'SA70 7JD',
      CountryName: 'United Kingdom',
      CountryIso2: 'GB',
      CountryIso3: 'GBR',
      CountryIsoNumber: 826,
      SortingNumber1: '84144',
      SortingNumber2: '',
      Barcode: '(SA707JD2T3)',
      POBoxNumber: '',
      Label:
        'Piccardy Flat\nKoolabar\nUpper Frog Street\nDINBYCH-Y-PYSGOD\nSA70 7JD\nUNITED KINGDOM',
      Type: 'Residential',
      DataLevel: 'Premise',
      Field1: '',
      Field2: '',
      Field3: '',
      Field4: '',
      Field5: '',
      Field6: '',
      Field7: '',
      Field8: '',
      Field9: '',
      Field10: '',
      Field11: '',
      Field12: '',
      Field13: '',
      Field14: '',
      Field15: '',
      Field16: '',
      Field17: '',
      Field18: '',
      Field19: '',
      Field20: '',
    },
  ],
};
