export const suggestions = {
  Items: [
    {
      Id: 'GB|RM|A|21415581',
      Type: 'Address',
      Text: 'Piccardy Flat, Koolabar, Upper Frog Street',
      Highlight: '0-13',
      Description: 'Tenby, SA70 7JD',
    },
    {
      Id: 'GB|RM|ENG|WHITCHURCH---STREET-ST._MARYS--PICCADILLY',
      Type: 'Street',
      Text: 'Piccadilly St. Marys Street',
      Highlight: '0-10',
      Description: 'Whitchurch, SY13 1RB - 2 Addresses',
    },
    {
      Id: 'GB|RM|ENG|TAMWORTH-PICCADILLY',
      Type: 'Locality',
      Text: 'Piccadilly, Tamworth, B78',
      Highlight: '0-10',
      Description: '174 Addresses',
    },
    {
      Id: 'GB|RM|ENG|CARDIFF---CLOSE-PICCA',
      Type: 'Street',
      Text: 'Picca Close',
      Highlight: '0-5',
      Description: 'Cardiff, CF5 - 128 Addresses',
    },
    {
      Id: 'GB|RM|ENG|BRADFORD----PICCADILLY',
      Type: 'Street',
      Text: 'Piccadilly',
      Highlight: '0-5',
      Description: 'Bradford, BD1 - 116 Addresses',
    },
    {
      Id: 'GB|RM|ENG|COWBRIDGE-LLANBLETHIAN---PICCADILLY',
      Type: 'Street',
      Text: 'Piccadilly',
      Highlight: '0-5',
      Description: 'Llanblethian, Cowbridge, CF71 7JL - 19 Addresses',
    },
    {
      Id: 'GB|RM|ENG|MONTROSE----PICCADILLY',
      Type: 'Street',
      Text: 'Piccadilly',
      Highlight: '0-5',
      Description: 'Montrose, DD10 8TH - 13 Addresses',
    },
    {
      Id: 'GB|RM|ENG|DONCASTER-BENTLEY---PICCADILLY',
      Type: 'Street',
      Text: 'Piccadilly',
      Highlight: '0-5',
      Description: 'Bentley, Doncaster, DN5 0BQ - 2 Addresses',
    },
    {
      Id: 'GB|RM|ENG|GRIMSBY-NEW_WALTHAM---PICCADILLY',
      Type: 'Street',
      Text: 'Piccadilly',
      Highlight: '0-5',
      Description: 'New Waltham, Grimsby, DN36 4YQ - 4 Addresses',
    },
    {
      Id: 'GB|RM|ENG|STROUD----PICCADILLY',
      Type: 'Street',
      Text: 'Piccadilly',
      Highlight: '0-5',
      Description: 'Stroud, GL5 1HB - 2 Addresses',
    },
  ],
};
