name: Release
on: [push]

env:
  CI: true

jobs:
  lint-test-build:
    name: Lint, test and build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Set up Node.js
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: 24

      - uses: pnpm/action-setup@eae0cfeb286e66ffb5155f1a79b90583a127a68b # v2.4.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: true

      - name: Check formatting and typing
        run: pnpm check

      - name: Test
        run: pnpm run test:ci

      - name: Build
        run: pnpm build

  release:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    environment: release
    needs: lint-test-build
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 0

      - name: Install node.js
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: 24

      - uses: pnpm/action-setup@eae0cfeb286e66ffb5155f1a79b90583a127a68b # v2.4.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: true

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c # v3.5.0
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Upgrade npm for trusted publishing
        run: npm i -g npm@^11.11.0

      - name: Create and publish versions
        uses: changesets/action@6a0a831ff30acef54f2c6aa1cbbc1096b066edaf # v1.7.0
        with:
          title: 'Release new version'
          commit: 'update version'
          publish: pnpm publish:ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
